// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdu-qHBYOcEJ9ot4-1FvlfysNOEEoZaU4',
    appId: '1:679678129488:web:cc91a8cb27e44b72f32855',
    messagingSenderId: '679678129488',
    projectId: 'permissions-app-7a4ce',
    authDomain: 'permissions-app-7a4ce.firebaseapp.com',
    storageBucket: 'permissions-app-7a4ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAVgQB7HEuiZW9YJLj0tbINg1TYJBt14g',
    appId: '1:679678129488:android:2a7d12af1271db77f32855',
    messagingSenderId: '679678129488',
    projectId: 'permissions-app-7a4ce',
    storageBucket: 'permissions-app-7a4ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh0zA5P6zBYXexfG5tVhb9c0siY3chRmo',
    appId: '1:679678129488:ios:48628ccd98f9a7b5f32855',
    messagingSenderId: '679678129488',
    projectId: 'permissions-app-7a4ce',
    storageBucket: 'permissions-app-7a4ce.appspot.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh0zA5P6zBYXexfG5tVhb9c0siY3chRmo',
    appId: '1:679678129488:ios:f0a51c5349265a1df32855',
    messagingSenderId: '679678129488',
    projectId: 'permissions-app-7a4ce',
    storageBucket: 'permissions-app-7a4ce.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdu-qHBYOcEJ9ot4-1FvlfysNOEEoZaU4',
    appId: '1:679678129488:web:42126b38d06eb115f32855',
    messagingSenderId: '679678129488',
    projectId: 'permissions-app-7a4ce',
    authDomain: 'permissions-app-7a4ce.firebaseapp.com',
    storageBucket: 'permissions-app-7a4ce.appspot.com',
  );

}